"""
Self-Reflection Service
After the main LLM generates an answer, this service acts as a second-pass
quality checker. It verifies the answer is grounded, dialect-correct, and
accurate — and optionally rewrites it if it fails any check.
"""

import httpx
from api.config import GROQ_API_KEY

# Use the faster model for reflection — it's a simpler verification task
REFLECTION_SYSTEM_PROMPT = """\
You are a strict quality checker for a nursery chatbot reply. You will be given:
1. CONTEXT: The only allowed facts
2. USER QUESTION: What the user asked
3. BOT ANSWER: The reply generated by the chatbot

Your job: Check the bot answer against these 3 rules:
RULE 1 - GROUNDED: Every fact MUST exist in the CONTEXT. No invented prices or rules.
RULE 2 - LANGUAGE MATCHING: 
  - If the USER QUESTION is in English, the BOT ANSWER MUST be in English.
  - If the USER QUESTION is in Arabic, the BOT ANSWER MUST be in warm Egyptian Colloquial Arabic.
RULE 3 - FORMAT & NAME: 
  - The answer MUST be formatted as concise bullet points. No large blocks of text.
  - The nursery MUST be called "Adam's & Elbaraa Nursery" or "حضانة آدمز والبراء". NEVER use words like "الناصرة".

If ALL 3 rules pass -> Reply with exactly: PASS
If ANY rule fails -> Reply with: FAIL
Then on the VERY NEXT LINE write a corrected answer that:
- Matches the user's exact language.
- Uses short bullet points (•).
- Uses the correct nursery name.
"""



async def reflect_and_validate(question: str, answer: str, context: str) -> str:
    """
    Runs self-reflection on the bot's generated answer.

    - If the answer passes all checks → return it unchanged.
    - If it fails → return the corrected version from the reflection model.
    - On any error → return the original answer (fail-safe).
    """
    headers = {
        "Authorization": f"Bearer {GROQ_API_KEY}",
        "Content-Type": "application/json"
    }

    review_prompt = f"""\
CONTEXT (the ONLY allowed facts):
{context}

USER QUESTION: {question}

BOT ANSWER: {answer}

Now apply the 3 rules and respond with PASS or FAIL + correction.
"""

    payload = {
        "model": REFLECTION_MODEL,
        "messages": [
            {"role": "system", "content": REFLECTION_SYSTEM_PROMPT},
            {"role": "user", "content": review_prompt}
        ],
        "temperature": 0.0,
        "max_tokens": 1000,
    }

    try:
        async with httpx.AsyncClient(timeout=8.0) as client:
            response = await client.post(
                "https://api.groq.com/openai/v1/chat/completions",
                json=payload,
                headers=headers
            )
            if response.status_code == 200:
                reflection_text = (
                    response.json()["choices"][0]["message"]
                    .get("content", "")
                    .strip()
                )

                if reflection_text.upper().startswith("PASS"):
                    print("✅ Reflection: PASS — answer is grounded and correct.")
                    return answer

                if reflection_text.upper().startswith("FAIL"):
                    lines = reflection_text.split("\n", 1)
                    if len(lines) > 1 and lines[1].strip():
                        corrected = lines[1].strip()
                        print("🔄 Reflection: FAIL — answer was corrected.")
                        return corrected
                    else:
                        print("⚠️ Reflection: FAIL but no corrected answer provided — keeping original.")
                        return answer

    except Exception as e:
        print(f"⚠️ Reflection error (keeping original answer): {e}")

    # Fail-safe: always return original if anything goes wrong
    return answer
